### ISSUE TITLE
Migrate NNPDEHan from NeuralPDE.jl

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/HighDimPDE.jl#25]
While NNPDENS with Euler-Maruyama is similar, it is a different algorithm as Han does the expansion to layers-per-step instead of repeated layers. I think keeping this difference for future discovery of its effect on stability of the training processes is an interesting piece.

**Comment by vboussange** [comment]
This is something addressed in https://github.com/SciML/NeuralPDE.jl/issues/514. Let me know if I can close this issue now.
