### ISSUE TITLE
How many paths are used with the DeepSplitting algorithm?

### ISSUE THREAD

**Issue by marcofrancis** [SciML/HighDimPDE.jl#48]
Hi,
Is there a parameter to control how many paths are simulated within the Deep Splitting algorithm?
Furthermore, is there a parameter that controls how many points (x_0) are generated when solving the problem on a hypercube?

**Comment by vboussange** [comment]
@marcofrancis the number of "paths" (stochastic trajectories) corresponds to the keyword `batch_size` used ni the `solve` function. `batch_size`determines the number of `x0` generated in the hypercube.

**Comment by marcofrancis** [comment]
Mmm, OK, so do I understand correctly that `batch_size` controls both the number of `x0` generated and the number of trajectories starting from these `x0`s?

**Comment by vboussange** [comment]
Yes
